---
kind: pipeline
name: default

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn test

  - name: docker
    image: plugins/docker
    settings:
    environment:
      TOKEN:
        from_secret: token
      repo: registry.nathaniallubitz.com/bots/banterbot
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
    build_args_from_env:
      - TOKEN
    secrets: [token]
    when:
      event:
        - push

  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    deployment: banter-bot
    container: banterbot
    repo: registry.nathaniallubitz.com/bots/banterbot
    kubernetes_server: https://kube.nathaniallubitz.com

trigger:
  branch:
    - main

---
kind: pipeline
name: deploy

steps:
  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    deployment: banter-bot
    container: banterbot
    repo: registry.nathaniallubitz.com/bots/banterbot
    kubernetes_server: https://kube.nathaniallubitz.com

trigger:
  target:
    - production
