---
kind: pipeline
name: default

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn test

  - name: docker
    image: plugins/docker
    settings:
      repo: bots/banterbot
      tags: latest
      registry: registry.nathaniallubitz.com
      build_args_from_env:
        - TOKEN
    when:
      event:
        - push

trigger:
  branch:
    - main
