---
kind: pipeline
name: default

steps:
  - name: build
    image: node:14.5.0-alpine3.10
    commands:
      - yarn test
    when:
      event:
        - push
        - pull_request

  - name: docker
    image: plugins/docker
    environment:
      TOKEN:
        from_secret: TOKEN
    settings:
      repo: registry.nathaniallubitz.com/bots/banterbot
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
      build_args_from_env:
        - TOKEN
    when:
      event:
        - push

  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_user: drone
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_server: http://kube.nathaniallubitz.com
    kubernetes_cert:
      from_secret: kubernetes_cert
    deployment: banter-bot
    container: banterbot
    namespace: default
    repo: registry.nathaniallubitz.com/bots/banterbot
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [kubernetes_token, kubernetes_cert]
    # commands:
    # - kubectl -n default set image deployment/banter-bot banterbot=registry.nathaniallubitz.com/bots/banterbot:${DRONE_COMMIT_SHA:0:8}
    when:
      event:
        - push

trigger:
  branch:
    - main

---
kind: pipeline
name: deploy

steps:
  - name: Deploy to Kubernetes
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_user: drone
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_server: http://kube.nathaniallubitz.com
    kubernetes_cert:
      from_secret: kubernetes_cert
    deployment: banter-bot
    container: banterbot
    namespace: default
    repo: registry.nathaniallubitz.com/bots/banterbot
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [kubernetes_token, kubernetes_cert]
    # commands:
    # - kubectl -n default set image deployment/banter-bot banterbot=registry.nathaniallubitz.com/bots/banterbot:${DRONE_COMMIT_SHA:0:8}

trigger:
  target:
    - production
